### PR TITLE
Added MariaDB as an option for database

### PR DESCRIPTION
**Pull request by ShayanGsh**
Updated the comments in the default config.yml too.

### CODE REVIEW

**Comment by ShayanGsh** [comment]
I'll fix this

**Comment by ChanceSD** [comment]
> I'll fix this

It's just missing an else on some of the if statements, I can fix it after merge if you want

**Comment by ShayanGsh** [comment]
I think this ought to fix it

**Comment by ShayanGsh** [comment]
Uh I don't know why it happened again, if you could fix it, I'd be thankful

**Comment by ChanceSD** [comment]
Everything else is fine, thank you very much for the PR

**Comment by ShayanGsh** [comment]
Glad to have helped. Thank you for being friendly and also for your project, it's the best PVP plugin out there.

**Pull request merged**
